import os
import sys
from PIL import Image
import numpy
from math import *

#user parameters
im1 = Image.open('1.jpg')
im2 = Image.open('2.jpg')
im3 = Image.open('3.jpg')
pack   = 8
dwidth = 256
width  = im1.size[0]
height = im1.size[1]

print("Width then height")
print(width)
print(height)

frame_size=int(width*height/pack)
frame_offset=2**ceil(log2(frame_size))
entire_ram = (2**ceil(log2(3)))*frame_offset
pack_to = frame_offset-frame_size;
finish_off=entire_ram-3*frame_offset
bram_size=ceil(log2(entire_ram));

print(str(hex(frame_size)))
print(str(hex(frame_offset)))
print(str(pack_to))
print(str(entire_ram))
print(str(finish_off))

#Array of RGB values now
dat1 = numpy.asarray(im1)
dat2 = numpy.asarray(im2)
dat3 = numpy.asarray(im3)
#[zero is RED?, 2 is blue??]


fp=open("framestreamer_img_pkg.vhd","w")
fp.write("--Autogenerated, don't touch\n")
fp.write("library IEEE; use IEEE.std_logic_1164.all; use IEEE.numeric_std.all;\n")
fp.write("package framestreamer_img_pkg is\n")
fp.write("type ram_t is array(0 to "+str(entire_ram)+"-1) of std_logic_vector("+str(dwidth)+"-1 downto 0);\n")
fp.write("constant ram_img : ram_t := (\n")


addr = 0
printten=50

pix = [0]*3
for k in range(0,3):
    for i in range(0,height):
        c=0
        s=""
        for j in range(0, width):
            if(k==0):
                pix[0]=dat1[i][j][2]
                pix[1]=dat1[i][j][1]
                pix[2]=dat1[i][j][0]
            elif(k==1):
                pix[0]=dat2[i][j][2]
                pix[1]=dat2[i][j][1]
                pix[2]=dat2[i][j][0]
            elif(k==2):
                pix[0]=dat3[i][j][2]
                pix[1]=dat3[i][j][1]
                pix[2]=dat3[i][j][0]
            
            c=c+1
            z="00"+format(pix[2],'02x')+format(pix[1],'02x')+format(pix[0],'02x')
            
            if(printten!=0):
                printten-=1
                print(z)
            z=z.replace("0x","")
            s=z+s
                
            if(c==pack):
                c=0
                line = str(addr) + " => x\""+s+"\","
                s=""
                addr = addr + 1
                fp.write(line+"\n")
                if(printten!=0):
                    print(line)

    for i in range(0,pack_to):
        line = str(addr) + " => (others => '0'),"
        addr = addr + 1
        fp.write(line+"\n")

for x in range(0,finish_off):
        if(addr != entire_ram-1):
            line = str(addr) + " => (others => '0'),"
        else:
            line = str(addr) + " => (others => '0'));"
        addr = addr + 1
        fp.write(line+"\n")
fp.write("end framestreamer_img_pkg;\n")
print("Done")